# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sadaqwed

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://www.powertyp.com//
        username: ${{ secrets.AzureAppService_ContainerUsername_6fd809bb219149ec8aa58ac710343460 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e13e823a403f47f59e3600b35b63c7a0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: www.powertyp.com//${{ secrets.AzureAppService_ContainerUsername_6fd809bb219149ec8aa58ac710343460 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sadaqwed'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_abc6cfb55af8467e9912d0bd971d5562 }}
        images: 'www.powertyp.com//${{ secrets.AzureAppService_ContainerUsername_6fd809bb219149ec8aa58ac710343460 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'